language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
dist: xenial
env:
  PYTHONPATH=.
before_install:
  - pip install pytest pytest-asyncio pytest-cov
  - pip install coveralls
install:
  - python setup.py -q install
script: pytest --verbose --cov=atools
after_success:
  - coveralls
deploy:
  provider: pypi
  user: cevans87
  password:
    secure: TJfsXGtd6qcj9YmxlXmQnycdoopvqe1LhyB05UtNyeWgWQ6uKRao2HVIoWRlunlSgNSp5OkwBIV+xo8XP8wScWORsEjXIdfGahHdDqL8iEI89kqnZlS+Y+yv8nImneCf8jGieua5cm+WscJNut1YjBZPcOlfEavNZ0GKHGb0FXmD5BgSKuqd+gSdep/TciD7QIV4xV3UviGWpmnhBflrhIfErCU2XFUh9LCDPZthuizc4cOnEYJYR3fubZTvVhCizfh123nr9tkQBIkr5WKGgwbXvCwV4U7gQllnNRYRX+ELPM7TJc1zz9N0qX0hMUzbYDfULo3SSRyaoMOP5/BhpdmlgNAyethf8V3mbHaul3YnnO39aVTcdVSIa0lIOIwsgtmshlF8OdTU63+mOi7yzrAd1DfaVFVTtGvuMFlzBKhsFxKqfLYW+FEjSll/xLzVpQGcHsdTUSygJN+7EYiXesS6HNpGkYFZzxLdFgah9Y5NASbNG/4wv7AmZnhA/dxKCjIrKzWujXNss1FgC/lcSeiPiXBrbJR+4Xk/Yk3l3Q8i69jwtIRCsWoZhyWZFfg2XOCXvEZK69jTQ8Pv6fug22PXYmHLMZkqJwTHaysxXj2iykaL/tweGUlHYExGhvNV6mNfZfivuTBuarG5Q3pkZKebgCOnKv5jOC3/w+8zLK8=
  on:
    tags: true
